#!/bin/bash

source_file_path=''
target_directory=''
create=false

processArguments() {
    while [ $# -gt 0 ]; do
        case $1 in
            --help)
                echo 'usage'
                exit 0
                ;;
            --create)
                create=true
                ;;
            *)
                if [ "$source_file_path" = '' ]; then
                    source_file_path=$1
                    # echo "$source_file_path"
                else
                    target_directory=$1
                fi
                ;;
        esac
        shift
    done

    if [ "$target_directory" = '' ]; then
        if [[ -z "$AWS_DEFAULT_PATH" ]]; then
            echo 'Target directory not specified'
            exit 1
        else target_directory=$AWS_DEFAULT_PATH
        fi
    fi

}

checkFile() {
    # 1. Check if file exists at given location
    if [[ ! -f $1 ]]; then
        echo "The specified file does not exist"
        return 1
    fi
}

login() {
    if ! aws sts get-caller-identity --profile aws-admin > /dev/null 2>&1; then
        echo 'User not logged in to AWS. Logging in...'
        if ! aws sso login --profile $AWS_PROFILE; then
            echo 'Please setup your credentials. Learn more at https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html'
            return 1
        fi
    fi
    echo 'User logged in'
    return 0
}

upload() {
    # 4. Upload file
    aws s3 cp $source_file_path $target_directory --profile $AWS_PROFILE
}

main() {
    # 2. Check if logged in, if not, log in
    if checkFile "$source_file_path"; then
        if login; then
            upload   
        fi
    else return 1
    fi
}

processArguments "$@"

echo "$AWS_PROFILE"

main


# main

# 4.1 Status progress bar

# 4.2 If file exists, ask to overwrite or rename

# 4.3 use encryption

# 4.4 Sucess or error message

# 4.5 Return shareable like post download